In [186]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Input
from sklearn.metrics import accuracy_score
import numpy as np

In [187]:
df=pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [189]:
df.duplicated().sum()

np.int64(0)

In [190]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [191]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [192]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [193]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True,dtype=int)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [194]:
x=df.drop(columns=['Exited'])
y=df['Exited']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

scalar=StandardScaler()
x_train_scaled=scalar.fit_transform(x_train)
x_test_scaled=scalar.transform(x_test)

In [195]:
model= Sequential([Input(shape=(11,))])
model.add(Dense(3,activation='sigmoid'))
model.add(Dense(3,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [196]:
model.summary()

Model: "sequential_23"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_64 (Dense)                │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_65 (Dense)                │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_66 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 52 (208.00 B)

 Trainable params: 52 (208.00 B)

 Non-trainable params: 0 (0.00 B)

In [197]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [202]:
model.fit(x_train_scaled,y_train,epochs=15)

Epoch 1/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4135
Epoch 2/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4080
Epoch 3/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4071
Epoch 4/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3991
Epoch 5/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3991
Epoch 6/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4145
Epoch 7/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3976
Epoch 8/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4129
Epoch 9/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3972
Epoch 10/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3917
Epoch 11/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3944
Epoch 12/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4016
Epoch 13/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4018
Epoch 14/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3933
Epoch 15/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4011

In [203]:
log=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [204]:
pred=np.where(log>0.5,1,0)

In [205]:
accuracy_score(y_test,pred)

0.581